name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  lottie: ^2.1.0
  get_storage: ^2.0.3
  introduction_screen: ^3.1.1
  intl: ^0.17.0
  avatar_glow: ^2.0.2
  emoji_picker_flutter: ^1.5.1
  flutter_launcher_icons: ^0.11.0
  google_sign_in: ^5.4.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

